lobby-world: 'world'
always-day: true
always-clear-weather: true
disable-hunger: true
disable-damage: true
disable-block-break: true
disable-block-place: true
disable-drop-item: true
disable-item-interaction: true
disable-item-move-in-inventory: true
disable-item-durability: true
disable-pickup-items: true
disable-explosions: true
disable-death-messages: true
clear-drops-on-death: true
clear-inventory-on-join: true
void-tp-to-spawn: true
use-world-spawn: true
disable-mob-spawning: true
disable-animal-spawning: true
enable-motd: true
enable-slime-pads: true